server:
  port: 8087

spring:
  application:
    name: API-GATEWAYS
  cloud:
    gateway:
      routes:
        - id: student
          uri: lb://student
          predicates:
            - Path=/student/**
        - id: school
          uri: lb://school           
          predicates:
            - Path=/school/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost